spring:
    profiles.active: local

server.port: 8082

---
spring:
    profiles: local
quote:
    url: https://gturnquist-quoters.cfapps.io/api/random

---
spring:
    profiles: test
quote:
    url: https://localhost:8090/